name: Bot San Hang

on:
  schedule:
    - cron: '*/45* * * *'
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install libraries
        run: pip install requests beautifulsoup4 python-dotenv google-genai

      - name: Run script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python crawl.py

      - name: Commit and Push Data
        run: |
          git config --global user.name 'Bot San Hang'
          git config --global user.email 'bot@noreply.github.com'
          git add product_list.csv
          git commit -m "Update product data" || exit 0
          git push
