name: Bot San Hang

on:
  schedule:
    - cron: '*/15 * * * *' # Chạy mỗi 30 phút (Bạn có thể sửa thành 15 hoặc 60)
  workflow_dispatch: # Cho phép bấm nút chạy thủ công để test

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install libraries
      run: pip install requests beautifulsoup4

    - name: Run script
      env: # Lấy bí mật nạp vào biến môi trường
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python crawl.py

    - name: Commit and Push Data # Bước này để lưu file csv cập nhật lại GitHub
      run: |
        git config --global user.name 'Bot San Hang'
        git config --global user.email 'bot@noreply.github.com'
        git add danh_sach_san_pham.csv
        git commit -m "Update data" || exit 0
        git push